//
//  AuthenticationOperation.swift
//  AltStore
//
//  Created by Riley Testut on 6/5/19.
//  Copyright © 2019 Riley Testut. All rights reserved.
//

@preconcurrency import UIKit
import Foundation
import Network
import CoreData
@preconcurrency import AltStoreCore
@preconcurrency import AltSign

enum RevokeDecision: Sendable {
    case revokeAll
    case keepExisting
}

private class AnisetteDataProvider {
    private let context: AuthenticatedOperationContext
    private let progress: Progress?
    
    private var lastFetchedData: ALTAnisetteData?
    private var lastFetchTime: Date?
    
    init(context: AuthenticatedOperationContext, progress: Progress?) {
        self.context = context
        self.progress = progress
        
        let authContext = context
        if let session = authContext.session {
            self.lastFetchedData = session.anisetteData
            self.lastFetchTime = session.anisetteData.date
        }
    }
    
    func getAnisetteData() async throws -> ALTAnisetteData {
        if let lastFetchedData = lastFetchedData,
           let lastFetchTime = lastFetchTime,
           lastFetchTime.timeIntervalSinceNow >= -40.0 {
            return lastFetchedData
        }
        
        let data = try await FetchAnisetteDataOperation(context: self.context).execute(parentProgress: self.progress)
        self.lastFetchedData = data
        self.lastFetchTime = Date()
        return data
    }
}

typealias AuthenticationError = AuthenticationErrorCode.Error
enum AuthenticationErrorCode: Int, ALTErrorEnum, CaseIterable {
    case noTeam
    case noCertificate
    case teamSelectorError
    
    case missingPrivateKey
    case missingCertificate
    
    case certificateLimitReachedFree
    case certificateLimitReachedPaid
    
    var errorFailureReason: String {
        switch self {
        case .noTeam: return NSLocalizedString("Your Apple ID has no developer teams?", comment: "")
        case .noCertificate: return NSLocalizedString("The developer certificate could not be found.", comment: "")
        case .teamSelectorError: return NSLocalizedString("Error presenting team selector view.", comment: "")
        case .missingPrivateKey: return NSLocalizedString("The certificate's private key could not be found.", comment: "")
        case .missingCertificate: return NSLocalizedString("The certificate could not be found.", comment: "")
        case .certificateLimitReachedFree: return NSLocalizedString("You have already exhausted the limit of 1 certificate for free developer accounts. Please revoke the existing certificate and try again.", comment: "")
        case .certificateLimitReachedPaid: return NSLocalizedString("You have already exhausted the maximum certificates that can be generated by a paid developer account. Please revoke at least one certificate and try again.", comment: "")
        }
    }
}

struct AuthenticationResult {
    let team: ALTTeam
    let certificate: ALTCertificate?
    let session: ALTAppleAPISession
}

private struct SessionCache {
    let team: ALTTeam
    let session: ALTAppleAPISession
}

final class AuthenticationOperation: BaseStandaloneOperation<AuthenticatedOperationContext, AuthenticationResult>, @unchecked Sendable {
    
    private var appleIDEmailAddress: String?
    private var appleIDPassword: String?
    private var shouldShowInstructions = false
    
    private let operationQueue = OperationQueue()
    
    let skipDeviceRegistration: Bool
    let skipCertificateProvisioning: Bool
    
    private lazy var anisetteDataProvider: AnisetteDataProvider = {
        AnisetteDataProvider(context: context, progress: self.progress)
    }()

    init(context: AuthenticatedOperationContext, skipDeviceRegistration: Bool = false, skipCertificateProvisioning: Bool = false) throws {
        self.skipDeviceRegistration = skipDeviceRegistration
        self.skipCertificateProvisioning = skipCertificateProvisioning

        try super.init(context: context)
        
        self.operationQueue.name = "com.altstore.AuthenticationOperation"
    }
    
    // Main Pipeline Execution
    
    override func execute(parentProgress: Progress?) async throws -> AuthenticationResult {
        debugLog("[AuthenticationOperation] execute() started")
        defer { debugLog("[AuthenticationOperation] execute() completed") }
        try await super.executePreconditionCheck(parentProgress: parentProgress)

        // Reset Keychain if email address changed
        if let newEmail = self.appleIDEmailAddress,
           let currentEmail = AuthManager.shared.currentAppleID,
           newEmail.lowercased() != currentEmail.lowercased() {
            self.verboseLog("[Authentication] Email address changed. Clearing cached session.")
            AuthManager.shared.clearSession()
        }

        // PHASE 1: Resolve valid session (Coalesced)
        let authResult = try await TaskChainCoalescer.shared.coalesce(key: "apple_auth") { () -> AuthenticationResult in
            // Check L1 - Session Cache
            if let session = AuthManager.shared.session,
               let team = AuthManager.shared.team {
                let cache = SessionCache(team: team, session: session)
                if let validatedResult = try await self.validateSessionCache(cache) {
                    return validatedResult
                }
            }
            
            // L2: Sign-in (Silent credentials sign-in or fallback to UI)
            return try await self.performNewSignIn()
        }
        
        self.context.team = authResult.team
        self.context.signingCertificate = authResult.certificate
        self.context.session = authResult.session

        // PHASE 2: Post-Authentication Work
        return try await self.performPostAuthenticationWork(result: authResult)
    }
    
    // Phase 1A: Session Cache Validation
    
    private func validateSessionCache(_ cache: SessionCache) async throws -> AuthenticationResult? {
        // Update anisette data if expired and provisioning is required
        if !self.skipCertificateProvisioning && cache.session.anisetteData.date.timeIntervalSinceNow < -40.0 {
            do {
                let anisetteData = try await self.anisetteDataProvider.getAnisetteData()
                cache.session.anisetteData = anisetteData
            } catch {
                self.verboseLog("[Authentication] Failed to update anisette data for cached session: \(error)")
            }
        }

        do {
            let certificates = try await AuthManager.shared.fetchCertificates(for: cache.team, session: cache.session)
            self.context.activeCertificates = certificates
            
            var certToUse: ALTCertificate?
            if let keychainCert = CertificateManager.shared.activeCertificate,
               certificates.contains(where: { $0.serialNumber == keychainCert.serialNumber }) {
                certToUse = keychainCert.certificate
            }
            
            if self.skipCertificateProvisioning || (certToUse != nil && certificates.contains(where: { $0.serialNumber == certToUse?.serialNumber })) {
                self.debugLog("[Authentication] SessionCache is valid. (using certificate: \(certToUse?.serialNumber ?? "nil"))")
             
                self.context.team = cache.team
                self.context.session = cache.session
                self.context.signingCertificate = certToUse
                return AuthenticationResult(team: cache.team, certificate: certToUse, session: cache.session)
            } else {
                self.debugLog("[Authentication] Cached/active certificate is no longer active on developer portal.")
            }
        } catch {
            self.debugLog("[Authentication] Failed to validate SessionCache: \(error)")
        }
        return nil
    }
    
    // Phase 1B: New Sign-In Flow
    
    private func performNewSignIn() async throws -> AuthenticationResult {
        let stepWeight: Int64 = self.skipDeviceRegistration ? 33 : 25
        
        self.verboseLog("[Authentication] execute: Invoking signIn...")
        let (account, session, signInTeam, signInCert) = try await self.signIn()
        self.debugLog("[Authentication] execute: signIn completed successfully.")
        self.context.session = session
        self.setProgress(stepWeight)
        if self.isCancelled { throw OperationError.cancelled }
        
        // Resolve Team
        let team: ALTTeam
        if let signInTeam = signInTeam {
            team = signInTeam
            self.context.team = team
            self.debugLog("[Authentication] execute: Using validated team '\(team.name)' from interactive auth.")
        } else {
            self.verboseLog("[Authentication] execute: Invoking fetchTeam...")
            team = try await self.fetchTeam(for: account, session: session)
            self.debugLog("[Authentication] execute: fetchTeam completed successfully.")
            self.context.team = team
        }
        
        self.debugLog("[Authentication] Saving team & account immediately after fetchTeam")
        AuthManager.shared.team = team
        AuthManager.shared.session = session
        try await self.save(team)
        
        // Check if custom/third-party certificate is active
        var isCustomCertActive = false
        if let activeCert = CertificateManager.shared.activeCertificate?.certificate,
           let data = activeCert.data {
            let details = SideStore.parseCertificate(derData: data)
            let belongsToAuthenticatedTeam = details.subject.contains(team.identifier) || details.issuer.contains(team.identifier)
            if !belongsToAuthenticatedTeam {
                self.debugLog("[Authentication] Custom/third-party active certificate detected (Subject OU does not match Team ID '\(team.identifier)').")
                isCustomCertActive = true
            }
        }
        
        // Resolve Certificate
        let certificate: ALTCertificate?
        if self.skipCertificateProvisioning || isCustomCertActive {
            if isCustomCertActive {
                self.debugLog("[Authentication] Using custom active certificate '\(CertificateManager.shared.activeCertificate?.certificate.serialNumber ?? "nil")' for signing. Bypassing portal fetch.")
            } else {
                self.verboseLog("[Authentication] execute: Skipping certificate provisioning.")
            }
            certificate = CertificateManager.shared.activeCertificate?.certificate
            self.context.signingCertificate = certificate
        } else {
            if let signInCert = signInCert {
                certificate = signInCert
                self.context.signingCertificate = certificate
                self.debugLog("[Authentication] execute: Using validated certificate '\(certificate?.serialNumber ?? "nil")' from interactive auth.")
            } else {
                self.verboseLog("[Authentication] execute: Invoking fetchCertificate...")
                certificate = try await self.fetchCertificate(for: team, session: session)
                self.debugLog("[Authentication] execute: fetchCertificate completed successfully. Serial: \(certificate?.serialNumber ?? "nil")")
                self.context.signingCertificate = certificate
            }
        }
        
        // Update active certificate if not using custom third-party cert
        if !isCustomCertActive {
            self.debugLog("[Authentication] Saving certificate after fetching certificate")
            try? CertificateManager.shared.setActiveCertificate(certificate)
        }
        
        return AuthenticationResult(team: team, certificate: certificate, session: session)
    }
    
    private func signIn() async throws -> (ALTAccount, ALTAppleAPISession, ALTTeam?, ALTCertificate?) {
        // Try Keychain Token Authentication
        if let adsid = AuthManager.shared.adsid, let xcodeToken = AuthManager.shared.xcodeToken {
            self.verboseLog("[AuthenticationOperation] Authenticating Apple ID with tokens...")
            do {
                let anisetteData = try await self.anisetteDataProvider.getAnisetteData()
                let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()
                let (account, session) = try await AuthManager.shared.authenticateWithToken(adsid: adsid, 
                                                                                            xcodeToken: xcodeToken, 
                                                                                            anisetteData: anisetteData, 
                                                                                            xcodeVersion: xcodeVersion)
                return (account, session, nil, nil)
            } catch {
                self.debugLog("[AuthenticationOperation] Authentication failed with token. Fall back to email and password login: \(error)")
            }
        }
        
        // Try Keychain Password Authentication
        if let appleID = AuthManager.shared.currentAppleID, let password = AuthManager.shared.password {
            self.debugLog("Authenticating Apple ID...")
            do {
                let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                self.appleIDPassword = password
                return (account, session, nil, nil)
            } catch ALTAppleAPIError.incorrectCredentials, ALTAppleAPIError.appSpecificPasswordRequired {
                let result = try await self.presentSignInUI()
                return (result.account, result.session, result.team, result.certificate)
            } catch {
                throw error
            }
        } else {
            // Present Interactive UI Prompt
            let result = try await self.presentSignInUI()
            return (result.account, result.session, result.team, result.certificate)
        }
    }
    
    private func presentSignInUI() async throws -> (account: ALTAccount, session: ALTAppleAPISession, team: ALTTeam, certificate: ALTCertificate?) {
        let handler = self.context.authenticationHandler
        
        self.verboseLog("[Authentication] presentSignInUI: Requesting credentials...")
        while true {
            let (appleID, password) = try await handler.credentials()
            if self.isCancelled { throw OperationError.cancelled }
            
            do {
                let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                self.debugLog("[Authentication] presentSignInUI: authenticate succeeded.")
                
                self.verboseLog("[Authentication] presentSignInUI: Fetching team...")
                let team = try await self.fetchTeam(for: account, session: session)
                self.debugLog("[Authentication] presentSignInUI: fetchTeam completed.")
                
                let certificate: ALTCertificate?
                var isCustomCertActive = false
                if let activeCert = CertificateManager.shared.activeCertificate?.certificate,
                   let data = activeCert.data {
                    let details = SideStore.parseCertificate(derData: data)
                    let belongsToAuthenticatedTeam = details.subject.contains(team.identifier) || details.issuer.contains(team.identifier)
                    if !belongsToAuthenticatedTeam {
                        isCustomCertActive = true
                    }
                }
                
                if self.skipCertificateProvisioning || isCustomCertActive {
                    certificate = CertificateManager.shared.activeCertificate?.certificate
                } else {
                    self.verboseLog("[Authentication] presentSignInUI: Fetching certificate...")
                    certificate = try await self.fetchCertificate(for: team, session: session)
                    self.debugLog("[Authentication] presentSignInUI: fetchCertificate completed.")
                }
                
                let result = (account, session, team, certificate)
                await handler.handleSignInResult(.success(result))
                
                self.shouldShowInstructions = true
                return (account, session, team, certificate)
            } catch {
                self.debugLog("[Authentication] presentSignInUI: Attempt failed with error: \(error)")
                await handler.handleSignInResult(.failure(error))
            }
        }
    }
    

    
    private func authenticate(appleID: String, password: String) async throws -> (ALTAccount, ALTAppleAPISession) {
        self.appleIDEmailAddress = appleID
        
        let anisetteData = try await self.anisetteDataProvider.getAnisetteData()
        let handler = self.context.authenticationHandler
        
        let verificationHandler: ((@escaping (String?) -> Void) -> Void)? = { completionHandler in
            Task {
                do {
                    let code = try await handler.verificationCode()
                    completionHandler(code)
                } catch {
                    completionHandler(nil)
                }
            }
        }
        
        let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()
        let (account, session) = try await AuthManager.shared.authenticate(
            appleID: appleID,
            password: password,
            anisetteData: anisetteData,
            xcodeVersion: xcodeVersion,
            verificationHandler: verificationHandler
        )
        
        AuthManager.shared.adsid = session.dsid
        AuthManager.shared.xcodeToken = session.authToken
        
        return (account, session)
    }
    
    // Team & Certificate Resolution Helpers
    
    private func fetchTeam(for account: ALTAccount, session: ALTAppleAPISession) async throws -> ALTTeam {
        let teams = try await AuthManager.shared.fetchTeams(for: account, session: session)
        
        let activeTeamFromDB = await DatabaseManager.shared.persistentContainer.performBackgroundTask { context in
            DatabaseManager.shared.activeTeam(in: context)
        }
        
        if let activeTeam = activeTeamFromDB, let altTeam = teams.first(where: { $0.identifier == activeTeam.identifier }) {
            return altTeam
        }
        
        return try await self.selectTeam(from: teams)
    }
    private func selectTeam(from teams: [ALTTeam]) async throws -> ALTTeam {
        if teams.count <= 1 {
            if let team = teams.first {
                return team
            } else {
                throw AuthenticationError(.noTeam)
            }
        }
        
        return try await self.context.authenticationHandler.resolveTeam(teams)
    }
    private func fetchCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let certificates = try await AuthManager.shared.fetchCertificates(for: team, session: session)
        self.context.activeCertificates = certificates
        
        let mainBundleCertSerial = Bundle.main.object(forInfoDictionaryKey: Bundle.Info.certificateID) as? String
        
        if let activeCert = CertificateManager.shared.activeCertificate,
           let certificate = certificates.first(where: { $0.serialNumber == activeCert.serialNumber }) {
            activeCert.certificate.machineIdentifier = certificate.machineIdentifier
            if let mainBundleCertSerial = mainBundleCertSerial, mainBundleCertSerial.lowercased() != activeCert.serialNumber.lowercased() {
                self.debugLog("[Authentication] Active certificate (\(activeCert.serialNumber)) and running bundle certificate (\(mainBundleCertSerial)) mismatch detected. Running Bundle Certificate is still active on the Paid account portal. Using active Keychain certificate.")
            }
            return activeCert.certificate
        }
        
        if let mainBundleCertSerial = mainBundleCertSerial,
           let certificate = certificates.first(where: { $0.serialNumber.lowercased() == mainBundleCertSerial.lowercased() }),
           let cert = CertificateManager.shared.getSignableCertificate(for: mainBundleCertSerial, externalPassword: mainBundleCertSerial) {
            cert.machineIdentifier = certificate.machineIdentifier
            self.debugLog("[Authentication] Using running bundle certificate (\(cert.serialNumber)) with valid private key from signable cache.")
            return cert
        }
        
        if certificates.isEmpty {
            // No certificates, so request a new one.
            return try await self.requestCertificate(for: team, session: session)
        } else {
            // We don't have private keys for any of the certificates,
            // so we need to revoke one and create a new one.
            return try await self.replaceCertificate(ourCertificates: certificates, for: team, session: session)
        }
    }
    private func requestCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let deviceName = await UIDevice.current.name
        let machineName: String = "SideStore - \(team.account.firstName)'s \(deviceName)"
        self.debugLog("[Authentication] requestCertificate: Starting request...")
        self.verboseLog("[Authentication] requestCertificate: Starting request for machineName '\(machineName)'...")
        do {
            self.verboseLog("[Authentication] requestCertificate: Calling AuthManager.shared.addCertificate...")
            let certificate = try await AuthManager.shared.addCertificate(machineName: machineName, to: team, session: session)
            self.verboseLog("[Authentication] requestCertificate: addCertificate succeeded. Serial: \(certificate.serialNumber)")
            self.verboseLog("[Authentication] requestCertificate: Fetching certificates to match...")
            let certificates = try await AuthManager.shared.fetchCertificates(for: team, session: session)
            self.context.activeCertificates = certificates
            self.verboseLog("[Authentication] requestCertificate: fetchCertificates returned \(certificates.count) certificates.")
            self.verboseLog("[Authentication] requestCertificate: Successfully retrieved certificate with private key.")
            return certificate
        } catch {
            self.debugLog("[Authentication] requestCertificate: Failed with error: \(error)")
            let underlying = error as NSError
            if underlying.domain == ALTAppleAPIErrorDomain && underlying.code == ALTAppleAPIError.tooManyCertificates.rawValue {
                let friendlyError: AuthenticationError = (team.type == .free) ? AuthenticationError(.certificateLimitReachedFree) : AuthenticationError(.certificateLimitReachedPaid)
                let wrappedError = NSError(
                    domain: (friendlyError as NSError).domain,
                    code: (friendlyError as NSError).code,
                    userInfo: [
                        NSLocalizedDescriptionKey: friendlyError.localizedDescription,
                        NSLocalizedFailureReasonErrorKey: friendlyError.failureReason ?? "",
                        NSUnderlyingErrorKey: underlying
                    ]
                )
                throw wrappedError
            } else {
                throw error
            }
        }
    }
    private func replaceCertificate(ourCertificates: [ALTX509Certificate], for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let filteredCertificates = ourCertificates.filter { a in
            a.machineName?.starts(with: "SideStore") == true || a.machineName?.starts(with: "AltStore") == true
        }
        self.debugLog("[Authentication] replaceCertificate: Starting. Total certs: \(ourCertificates.count), filtered: \(filteredCertificates.count)")
        
        if filteredCertificates.isEmpty {
            self.verboseLog("[Authentication] replaceCertificate: No filtered certificates. Requesting new...")
            return try await self.requestCertificate(for: team, session: session)
        }
        
        // We don't have private keys for any of the certificates,
        // so we need to revoke one and create a new one.
        var certsText = ""
        for certificate in filteredCertificates {
            if let name = certificate.machineName {
                certsText.append("\(name)\n")
            }
        }
        
        self.debugLog("[Authentication] replaceCertificate: Presenting revoke alert...")
        let action = try await self.context.authenticationHandler.resolveRevocation(certsText: certsText, teamType: team.type)
        self.debugLog("[Authentication] replaceCertificate: User action was \(action)")
        switch action {
        case .keepExisting:
            self.verboseLog("[Authentication] replaceCertificate: Keeping existing, calling requestCertificate...")
            return try await self.requestCertificate(for: team, session: session)
            
        case .revokeAll:
            self.debugLog("[Authentication] replaceCertificate: Revoking all filtered certificates...")
            var firstError: Error? = nil
            for certificate in filteredCertificates {
                do {
                    self.verboseLog("[Authentication] replaceCertificate: Revoking certificate '\(certificate.machineName ?? "nil")' (Serial: \(certificate.serialNumber))...")
                    try await AuthManager.shared.revokeCertificate(certificate, for: team, session: session)
                    self.verboseLog("[Authentication] replaceCertificate: Revoke succeeded.")
                } catch {
                    self.debugLog("[Authentication] replaceCertificate: Revoke failed with error: \(error)")
                    if firstError == nil {
                        firstError = error
                    }
                }
            }
            if let error = firstError {
                self.debugLog("[Authentication] replaceCertificate: Error occurred during revocation, throwing...")
                throw error
            } else {
                self.debugLog("[Authentication] replaceCertificate: All certificates successfully revoked. Requesting new certificate...")
                return try await self.requestCertificate(for: team, session: session)
            }
        }
    }


    
    // Phase 2: Post-Authentication Operations & Cleanup
    
    private func performPostAuthenticationWork(result: AuthenticationResult) async throws -> AuthenticationResult {
        let (team, certificate, session) = (result.team, result.certificate, result.session)
        let stepWeight: Int64 = self.skipDeviceRegistration ? 33 : 25
        
        do {
            self.setProgress(stepWeight * 2)
            if self.isCancelled { throw OperationError.cancelled }
            
            self.setProgress(stepWeight * 3)
            if self.isCancelled { throw OperationError.cancelled }
            
            if !self.skipDeviceRegistration {
                self.verboseLog("[Authentication] execute: Invoking registerCurrentDevice...")
                _ = try await self.registerCurrentDevice(for: team, session: session)
                self.debugLog("[Authentication] execute: registerCurrentDevice completed successfully.")
                self.setProgress(stepWeight * 4)
                if self.isCancelled { throw OperationError.cancelled }
            }
            
            self.setProgress(100)
            if self.isCancelled { throw OperationError.cancelled }
            
            self.verboseLog("[Authentication] execute: Invoking cacheAppIDs...")
            try await SyncAppIDsOperation(context: self.context).execute(parentProgress: progress)
            self.debugLog("[Authentication] execute: cacheAppIDs completed successfully.")
            
            self.verboseLog("[Authentication] execute: Invoking postAuthenticationCleanup with success...")
            try await self.postAuthenticationCleanup(result: .success(result))
            self.debugLog("[Authentication] execute: postAuthenticationCleanup completed successfully.")
            return result
        } catch {
            self.debugLog("[Authentication] execute: Caught error in post-auth flow: \(error). Cleaning up...")
            try? await self.postAuthenticationCleanup(result: .failure(error))
            throw error
        }
    }
    
    private func save(_ altTeam: ALTTeam) async throws {
        guard let context = self.context.dbBackgroundContext else {
            throw OperationError.invalidParameters("AuthenticationOperation: context.dbBackgroundContext is nil")
        }
        try await context.perform {
            try self.saveTeamAndAccount(altTeam, in: context)
        }
    }
    
    private func saveTeamAndAccount(_ altTeam: ALTTeam, makeActive: Bool = false, in context: NSManagedObjectContext) throws {
        let account: Account
        let team: Team
        
        if let tempAccount = Account.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Account.identifier), altTeam.account.identifier), in: context) {
            account = tempAccount
        } else {
            account = Account(altTeam.account, context: context)
        }
        
        if let tempTeam = Team.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Team.identifier), altTeam.identifier), in: context) {
            team = tempTeam
        } else {
            team = Team(altTeam, account: account, context: context)
        }
        
        account.update(account: altTeam.account)
        if let providedEmailAddress = self.appleIDEmailAddress {
            account.appleID = providedEmailAddress
        }
        
        team.update(team: altTeam)
        
        if makeActive {
            // Account
            account.isActiveAccount = true
            let otherAccountsFetchRequest = Account.fetchRequest() as NSFetchRequest<Account>
            otherAccountsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Account.identifier), account.identifier)
            let otherAccounts = try context.fetch(otherAccountsFetchRequest)
            for otherAccount in otherAccounts {
                otherAccount.isActiveAccount = false
            }

            // Team
            team.isActiveTeam = true
            let otherTeamsFetchRequest = Team.fetchRequest() as NSFetchRequest<Team>
            otherTeamsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Team.identifier), team.identifier)
            let otherTeams = try context.fetch(otherTeamsFetchRequest)
            for otherTeam in otherTeams {
                otherTeam.isActiveTeam = false
            }

            let isSparseRestorePatched   = ProcessInfo().sparseRestorePatched
            let isAppLimitDisabled       = UserDefaults.standard.isAppLimitDisabled

            UserDefaults.standard.activeAppsLimit = nil
            // TODO: @mahee96: is the minimum ver match for ios 13.3.1 check required?
            //                 if so what is the app limit? As nil app limit specifies unlimited apps?!
            if team.type == .free {
                if !isAppLimitDisabled && isSparseRestorePatched ||
                    isAppLimitDisabled && !isSparseRestorePatched 
                {
                        UserDefaults.standard.activeAppsLimit = InstalledApp.freeAccountActiveAppsLimit
                }
            }
            
            // Update keychain via AuthManager
            AuthManager.shared.currentAppleID = self.appleIDEmailAddress ?? altTeam.account.appleID // Prefer the user's provided email address over the one associated with their account (which may be outdated).
            if let appleIDPassword = self.appleIDPassword {
                AuthManager.shared.password = appleIDPassword
            }
        }
        
        try context.save()
    }
    
    private func postAuthenticationCleanup(result: Result<AuthenticationResult, Error>) async throws {
        self.verboseLog("[Authentication] postAuthenticationCleanup: Starting cleanup...")
        switch result {
        case .failure(let error):
            self.debugLog("[Authentication] postAuthenticationCleanup: Failure result - \(error.localizedDescription)")
            self.verboseLog("[AuthenticationOperation] Failed to authenticate account. \(error.localizedDescription)")
            
            self.verboseLog("[Authentication] postAuthenticationCleanup: Completing session (failure case)...")
            await self.context.authenticationHandler.complete()
            return
            
        case .success(let authResult):
            let team = authResult.team
            self.verboseLog("[Authentication] postAuthenticationCleanup: Authentication Success for team \(team.identifier) account.")
        }
        
        guard let context = self.context.dbBackgroundContext else {
            self.debugLog("[Authentication] postAuthenticationCleanup: Error - context.dbBackgroundContext is nil!")
            throw OperationError.invalidParameters("AuthenticationOperation: context.dbBackgroundContext is nil")
        }
        
        self.verboseLog("[Authentication] postAuthenticationCleanup: Performing database updates inside context...")
        do {
            let authResult = try result.get()
            try await context.perform {
                try self.saveTeamAndAccount(authResult.team, makeActive: true, in: context)
            }
        } catch {
            self.debugLog("[Authentication] postAuthenticationCleanup: error occured when performing cleanup: \(error)")
        }
        self.verboseLog("[Authentication] postAuthenticationCleanup: Database updates completed.")
        
        do {
            let authResult = try result.get()
            let (altTeam, altCertificate, session) = (authResult.team, authResult.certificate, authResult.session)
            if let altCertificate = altCertificate, !self.skipCertificateProvisioning {
                self.verboseLog("[Authentication] postAuthenticationCleanup: Checking instructions and resign alerts...")
                let didHandlePostAuth = await self.handlePostAuth()
                self.verboseLog("[Authentication] postAuthenticationCleanup: didHandlePostAuth = \(didHandlePostAuth)")
                
                let signer = ALTSigner(team: altTeam, certificate: altCertificate)
                // Resign screen must go last since a successful resign/reinstall will cause the app to quit.
                let didResign = await self.validateCodeSigning(signer: signer, session: session)
                self.verboseLog("[Authentication] postAuthenticationCleanup: didResign = \(didResign)")
                if !didResign {
                    try? CertificateManager.shared.setActiveCertificate(altCertificate)
                    self.verboseLog("[Authentication] postAuthenticationCleanup: Cached signing certificate in Keychain.")
                    
                    if self.context.isSideStoreResignDismissed && !didHandlePostAuth && self.shouldShowInstructions {
                        self.verboseLog("[Authentication] postAuthenticationCleanup: Resign was skipped during interactive auth. Showing instructions now.")
                        await self.context.authenticationHandler.resolvePostAuth()
                    }
                }
            }
        } catch {
            self.debugLog("[AuthenticationOperation] Skipping post-authentication alerts and certificate caching because authentication failed: \(error.localizedDescription)")
        }
        
        self.verboseLog("[Authentication] postAuthenticationCleanup: Completing session...")
        await self.context.authenticationHandler.complete()
    }
    

    
    private func registerCurrentDevice(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTDevice {
        guard let udid = try await fetchUDID() else {
            throw OperationError.unknownUDID
        }
        
        let devices = try await AuthManager.shared.fetchDevices(for: team, types: [.iphone, .ipad], session: session)
        if let device = devices.first(where: { $0.identifier == udid }) {
            return device
        } else {
            return try await AuthManager.shared.registerDevice(name: UIDevice.current.name, identifier: udid, type: .iphone, team: team, session: session)
        }
    }
    

    
    private func handlePostAuth() async -> Bool {
        self.verboseLog("[Authentication] handlePostAuth: entering method, shouldShowInstructions = \(self.shouldShowInstructions)")
        guard self.shouldShowInstructions else {
            self.verboseLog("[Authentication] handlePostAuth: shouldShowInstructions is false, returning false")
            return false
        }
        
        await self.context.authenticationHandler.resolvePostAuth()
        return true
    }
    
    private func validateCodeSigning(signer: ALTSigner, session: ALTAppleAPISession) async -> Bool {
        self.verboseLog("[Authentication] validateCodeSigning: entering method")
        guard let appBundle = ALTApplication(fileURL: Bundle.main.bundleURL), let provisioningProfile = appBundle.provisioningProfile else {
            self.verboseLog("[Authentication] validateCodeSigning: Application bundle or provisioning profile nil, returning false")
            return false
        }
        
        let result = CodeSignValidator.validate(
            runningProfile: provisioningProfile,
            activeCertificates: self.context.activeCertificates,
            signerCertificate: signer.certificate.x509,
            signerTeam: signer.team
        )
        
        switch result {
        case .success:
            self.verboseLog("[Authentication] validateCodeSigning: Validation succeeded, no resign required.")
            return false
            
        case .failure(let reason):
            self.debugLog("[Authentication] Signing certificate mismatch detected: \(reason)")
            
            // For Paid Developer accounts, if the certificate used to sign the current installation
            // is still active on Apple's portal (which shows as .privateKeyLost or .externalSigner),
            // we don't need to warn the user or force a resign.
            if signer.team.type != .free && (reason == .privateKeyLost || reason == .externalSigner) {
                self.debugLog("[Authentication] Running certificate is still active on the Paid account portal. Skipping resign screen.")
                return false
            }
            
            let handler = self.context.authenticationHandler
            do {
                let confirmed = try await handler.resolveResign(mismatchReason: reason, context: self.context)
                if !confirmed {
                    self.context.isSideStoreResignDismissed = true
                }
                return confirmed
            } catch {
                self.context.isSideStoreResignDismissed = true
                return false
            }
        }
    }
}
