//
//  AuthenticationOperation.swift
//  AltStore
//
//  Created by Riley Testut on 6/5/19.
//  Copyright © 2019 Riley Testut. All rights reserved.
//

@preconcurrency import UIKit
import Foundation
import Network
import CoreData
@preconcurrency import AltStoreCore
@preconcurrency import AltSign

enum RevokeDecision: Sendable {
    case revokeAll
    case keepExisting
}

private class AnisetteDataProvider {
    private static let ANISETTE_VALID_DURATION: TimeInterval = 40.0

    private let context: AuthenticatedOperationContext
    private let progress: Progress?
    
    private var lastFetchedData: ALTAnisetteData?
    
    init(context: AuthenticatedOperationContext, progress: Progress?) {
        self.context = context
        self.progress = progress
    }
    
    func getAnisetteData(for session: ALTAppleAPISession? = nil) async throws -> ALTAnisetteData {
        let currentAnisette = session?.anisetteData ?? self.lastFetchedData
        
        if let currentAnisette = currentAnisette,
           currentAnisette.date.timeIntervalSinceNow >= -Self.ANISETTE_VALID_DURATION 
        {
            return currentAnisette
        }
        
        let anisetteData = try await FetchAnisetteDataOperation(context: self.context)
                                        .execute(parentProgress: self.progress)

        self.lastFetchedData = anisetteData
        return anisetteData
    }
}

typealias AuthenticationError = AuthenticationErrorCode.Error
enum AuthenticationErrorCode: Int, ALTErrorEnum, CaseIterable {
    case noTeam
    case noCertificate
    case teamSelectorError
    
    case missingPrivateKey
    case missingCertificate
    
    case certificateLimitReachedFree
    case certificateLimitReachedPaid
    
    var errorFailureReason: String {
        switch self {
        case .noTeam: return NSLocalizedString("Your Apple ID has no developer teams?", comment: "")
        case .noCertificate: return NSLocalizedString("The developer certificate could not be found.", comment: "")
        case .teamSelectorError: return NSLocalizedString("Error presenting team selector view.", comment: "")
        case .missingPrivateKey: return NSLocalizedString("The certificate's private key could not be found.", comment: "")
        case .missingCertificate: return NSLocalizedString("The certificate could not be found.", comment: "")
        case .certificateLimitReachedFree: return NSLocalizedString("You have already exhausted the limit of 1 certificate for free developer accounts. Please revoke the existing certificate and try again.", comment: "")
        case .certificateLimitReachedPaid: return NSLocalizedString("You have already exhausted the maximum certificates that can be generated by a paid developer account. Please revoke at least one certificate and try again.", comment: "")
        }
    }
}

struct AuthenticationResult {
    let team: ALTTeam
    let certificate: ALTCertificate?
    let session: ALTAppleAPISession
    let portalCertificates: [ALTX509Certificate]?
}

private struct SessionCache {
    let team: ALTTeam
    let session: ALTAppleAPISession
}

final class AuthenticationOperation: BaseStandaloneOperation<AuthenticatedOperationContext, AuthenticationResult>, @unchecked Sendable {
    
    private var appleIDEmailAddress: String?
    private var appleIDPassword: String?
    private var requiresPostAuthFlow = false
    
    let skipDeviceRegistration: Bool
    let skipCertificateProvisioning: Bool
    
    private lazy var anisetteDataProvider: AnisetteDataProvider = {
        AnisetteDataProvider(context: context, progress: self.progress)
    }()

    init(context: AuthenticatedOperationContext, skipDeviceRegistration: Bool = false, skipCertificateProvisioning: Bool = false) throws {
        self.skipDeviceRegistration = skipDeviceRegistration
        self.skipCertificateProvisioning = skipCertificateProvisioning

        try super.init(context: context)
    }
    
    // Main Pipeline Execution
    override func execute(parentProgress: Progress?) async throws -> AuthenticationResult {
        debugLog("[AuthenticationOperation] execute() started")
        defer { debugLog("[AuthenticationOperation] execute() completed") }
        try await super.executePreconditionCheck(parentProgress: parentProgress)

        let authResult = try await TaskChainCoalescer.shared.coalesce(key: "apple_auth") { () -> AuthenticationResult in
            if let session = AuthManager.shared.session,
               let team = AuthManager.shared.team 
            {
                session.anisetteData = try await self.anisetteDataProvider.getAnisetteData(for: session)
                let certToUse = CertificateManager.shared.activeCertificate?.certificate
                
                // auth session doesn't expire soon, and since this isn't retained on restart, this should be fine.
                self.debugLog("[Authentication] Using cached session, team, certificate")
                return AuthenticationResult(
                    team: team, 
                    certificate: certToUse, 
                    session: session, 
                    portalCertificates: self.context.portalCertificates
                )
            }
            
            return try await self.startAuthentication()
        }
        
        self.context.team               = authResult.team
        self.context.signingCertificate = authResult.certificate
        self.context.session            = authResult.session
        self.context.portalCertificates = authResult.portalCertificates

        let result = try await self.finalizeAuthentication(result: authResult)

        self.setProgress(100)
        return result
    }
    
    private func startAuthentication() async throws -> AuthenticationResult {
        let (account, session) = if let silentResult = try await self.silentSignIn() {
            silentResult
        } else {
            try await self.authenticationLoop()
        }
        
        self.context.session = session
        self.setProgress(self.skipDeviceRegistration ? 33 : 25)
        if self.isCancelled { throw OperationError.cancelled }

        // 2. Resolve Team & Save State
        let team = try await self.fetchTeam(for: account, session: session)
        self.context.team = team
        AuthManager.shared.team = team
        AuthManager.shared.session = session
        try await self.saveTeamAndAccount(team)

        // 3. Resolve Certificate (Custom vs Developer Portal)
        let activeCert = CertificateManager.shared.activeCertificate?.certificate
        let isCustomCert = activeCert?.data.map { data in
            let details = parseCertificate(derData: data)
            return !details.subject.contains(team.identifier) && !details.issuer.contains(team.identifier)
        } ?? false

        if isCustomCert {
            self.debugLog("[Authentication] Custom active certificate detected (Subject OU mismatch with Team ID '\(team.identifier)'). Bypassing portal fetch.")
        }

        let certificate: ALTCertificate? = if self.skipCertificateProvisioning || isCustomCert {
            activeCert
        } else {
            try await self.fetchCertificate(for: team, session: session)
        }
        
        if !self.skipCertificateProvisioning && !isCustomCert {
            try? CertificateManager.shared.setActiveCertificate(certificate)
        }

        self.context.signingCertificate = certificate
        return AuthenticationResult(team: team, certificate: certificate, session: session, portalCertificates: self.context.portalCertificates)
    }
    
    private func silentSignIn() async throws -> (ALTAccount, ALTAppleAPISession)? {
        // Try silent auth using Keychain Token
        if let adsid = AuthManager.shared.adsid, 
           let xcodeToken = AuthManager.shared.xcodeToken 
        {
            self.verboseLog("[AuthenticationOperation] Authenticating Apple ID with tokens...")

            do {
                let anisetteData = try await self.anisetteDataProvider.getAnisetteData()
                let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()

                let (account, session) = try await AuthManager.shared.authenticateWithToken(
                    adsid: adsid, 
                    xcodeToken: xcodeToken, 
                    anisetteData: anisetteData, 
                    xcodeVersion: xcodeVersion
                )
                return (account, session)
            } catch {
                self.debugLog("[AuthenticationOperation] Token authentication failed: \(error)")
            }
        }
        
        // Try silent auth using Keychain Password
        if let appleID = AuthManager.shared.currentAppleID, 
           let password = AuthManager.shared.password 
        {
            self.debugLog("[AuthenticationOperation] Authenticating Apple ID with saved password...")
            do {
                let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                self.appleIDPassword = password
                return (account, session)
            } catch {
                self.debugLog("[AuthenticationOperation] Saved password authentication failed: \(error)")
            }
        }

        return nil
    }

    private func authenticationLoop() async throws -> (account: ALTAccount, session: ALTAppleAPISession) {
        self.verboseLog("[Authentication] authenticationLoop: Requesting credentials...")
        let handler = self.context.authenticationHandler
        
        while true {
            let (appleID, password) = try await handler.credentials()
            if self.isCancelled { throw OperationError.cancelled }
            
            do {
                let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                self.debugLog("[Authentication] authenticationLoop: authenticate succeeded.")
                
                await handler.handleSignInResult(.success((account, session)))
                
                self.requiresPostAuthFlow = true
                return (account, session)
            } catch {
                self.debugLog("[Authentication] authenticationLoop: Attempt failed with error: \(error)")
                await handler.handleSignInResult(.failure(error))
            }
        }
    }
    
    private func authenticate(appleID: String, password: String) async throws -> (ALTAccount, ALTAppleAPISession) {
        self.appleIDEmailAddress = appleID
        
        let anisetteData = try await self.anisetteDataProvider.getAnisetteData()
        let handler = self.context.authenticationHandler
        
        let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()

        let (account, session) = try await AuthManager.shared.authenticate(
            appleID: appleID,
            password: password,
            anisetteData: anisetteData,
            xcodeVersion: xcodeVersion
        ) { completionHandler in

            Task.detached {
                do {
                    let code = try await handler.verificationCode()
                    completionHandler(code)
                } catch {
                    completionHandler(nil)
                }
            }
        }
        
        AuthManager.shared.adsid = session.dsid
        AuthManager.shared.xcodeToken = session.authToken
        
        return (account, session)
    }

    private func finalizeAuthentication(result: AuthenticationResult) async throws -> AuthenticationResult {
        let (team, certificate, session) = (result.team, result.certificate, result.session)
        let stepWeight: Int64 = self.skipDeviceRegistration ? 33 : 25
        
        do {
            if self.isCancelled { throw OperationError.cancelled }
            
            if !self.skipDeviceRegistration {
                self.verboseLog("[Authentication] Registering current device...")
               
                let device = try await self.registerCurrentDevice(for: team, session: session)
                self.debugLog("[Authentication] Registered current device UDID: \(device.identifier).")
                
                self.setProgress(stepWeight * 3)
                if self.isCancelled { throw OperationError.cancelled }
            }
            
            try await self.postAuthenticationCleanup(result: .success(result))
            return result
        } catch {
            self.debugLog("[Authentication] execute: Caught error in post-auth flow: \(error). Cleaning up...")
            try? await self.postAuthenticationCleanup(result: .failure(error))
            throw error
        }
    }

    private func postAuthenticationCleanup(result: Result<AuthenticationResult, Error>) async throws {
        self.verboseLog("[Authentication] postAuthenticationCleanup: Starting cleanup...")
        
        switch result {
            case .failure(let error):
                self.debugLog("[Authentication] postAuthenticationCleanup: Failure result - \(error.localizedDescription)")
                await self.context.authenticationHandler.complete()
                self.verboseLog("[Authentication] postAuthenticationCleanup: invoked auth complete for .failure case...")
                
            case .success(let result):
                let team = result.team
                let certificate = result.certificate
                let session = result.session

                self.verboseLog("[Authentication] postAuthenticationCleanup: Authentication Success for team \(team.identifier) account.")
                do {
                    try await self.saveTeamAndAccount(team, makeActive: true)
                } catch {
                    self.debugLog("[Authentication] postAuthenticationCleanup: error occured when performing cleanup: \(error)")
                }
                self.verboseLog("[Authentication] postAuthenticationCleanup: Database updates completed.")
                
                if let signingCertificate = certificate, !self.skipCertificateProvisioning
                {
                    let signer = ALTSigner(team: team, certificate: signingCertificate)
                    let didResign = await self.validateCodeSign(signer: signer, session: session)
                    self.verboseLog("[Authentication] postAuthenticationCleanup: didResign = \(didResign)")
                    
                    if !didResign && self.requiresPostAuthFlow {
                        await self.context.authenticationHandler.resolvePostAuth()
                        self.verboseLog("[Authentication] postAuthenticationCleanup: post auth flow completed...")
                    }
                }
                
                await self.context.authenticationHandler.complete()
                self.verboseLog("[Authentication] postAuthenticationCleanup: invoked auth complete for .success case...")
        }
    }
}

// Persistence and Codesign Validity Check Helpers
private extension AuthenticationOperation {

    private func saveTeamAndAccount(_ altTeam: ALTTeam, makeActive: Bool = false) async throws {
        guard let context = self.context.dbBackgroundContext else {
            throw OperationError.invalidParameters("AuthenticationOperation: context.dbBackgroundContext is nil")
        }
        try await context.perform {
            let account: Account
            let team: Team
            
            if let tempAccount = Account.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Account.identifier), altTeam.account.identifier), in: context) {
                account = tempAccount
            } else {
                account = Account(altTeam.account, context: context)
            }
            
            if let tempTeam = Team.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Team.identifier), altTeam.identifier), in: context) {
                team = tempTeam
            } else {
                team = Team(altTeam, account: account, context: context)
            }
            
            account.update(account: altTeam.account)

            if let providedEmailAddress = self.appleIDEmailAddress {
                account.appleID = providedEmailAddress
            }
            
            team.update(team: altTeam)
            
            if makeActive {
                // Account
                account.isActiveAccount = true
                let otherAccountsFetchRequest = Account.fetchRequest() as NSFetchRequest<Account>
                otherAccountsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Account.identifier), account.identifier)
                let otherAccounts = try context.fetch(otherAccountsFetchRequest)
                for otherAccount in otherAccounts {
                    otherAccount.isActiveAccount = false
                }

                // Team
                team.isActiveTeam = true
                let otherTeamsFetchRequest = Team.fetchRequest() as NSFetchRequest<Team>
                otherTeamsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Team.identifier), team.identifier)
                let otherTeams = try context.fetch(otherTeamsFetchRequest)
                for otherTeam in otherTeams {
                    otherTeam.isActiveTeam = false
                }

                let isSparseRestorePatched   = ProcessInfo().sparseRestorePatched
                let isAppLimitDisabled       = UserDefaults.standard.isAppLimitDisabled

                UserDefaults.standard.activeAppsLimit = nil
                // TODO: @mahee96: is the minimum ver match for ios 13.3.1 check required?
                //                 if so what is the app limit? As nil app limit specifies unlimited apps?!
                if team.type == .free {
                    if !isAppLimitDisabled && isSparseRestorePatched ||
                        isAppLimitDisabled && !isSparseRestorePatched 
                    {
                        UserDefaults.standard.activeAppsLimit = InstalledApp.freeAccountActiveAppsLimit
                    }
                }
                
                // Update keychain via AuthManager

                // Prefer the user's provided email address over the one associated with their account (which may be outdated).
                AuthManager.shared.currentAppleID = self.appleIDEmailAddress ?? altTeam.account.appleID 
                if let appleIDPassword = self.appleIDPassword {
                    AuthManager.shared.password = appleIDPassword
                }
            }
            
            try context.save()
        }
    }
    
    private func validateCodeSign(signer: ALTSigner, session: ALTAppleAPISession) async -> Bool {
        self.verboseLog("[Authentication] validateCodeSign: entering method")
        guard let appBundle = ALTApplication(fileURL: Bundle.Info.activeBundleURL), 
              let provisioningProfile = appBundle.provisioningProfile else 
        {
            self.verboseLog("[Authentication] validateCodeSign: Application bundle or provisioning profile nil, returning false")
            return false
        }
        
        let result = CodeSignValidator.validate(
            runningProfile: provisioningProfile,
            portalCertificates: self.context.portalCertificates,
            signerCertificate: signer.certificate.x509,
            signerTeam: signer.team
        )
        
        switch result {
            case .success:
                self.verboseLog("[Authentication] validateCodeSign: Validation succeeded, no resign required.")
                return false
                
            case .failure(let reason):
                self.debugLog("[Authentication] Signing certificate mismatch detected: \(reason)")
                
                // For Paid Developer accounts, if the certificate used to sign the current installation
                // is still active on Apple's portal (which shows as .privateKeyLost or .externalSigner),
                // we don't need to warn the user or force a resign.
                if signer.team.type != .free && (reason == .privateKeyLost || reason == .externalSigner) {
                    self.debugLog("[Authentication] Running certificate is still active on the Paid account portal. Skipping resign screen.")
                    return false
                }
                
                let handler = self.context.authenticationHandler
                do {
                    return try await handler.resolveResign(mismatchReason: reason, context: self.context)
                } catch {
                    self.verboseLog("[Authentication] validateCodeSign: error occured when handling resolveResign error: \(error)")
                    return false
                }
        }
    }
}


// Team, Certificate Resolution & Device Registration Helpers
private extension AuthenticationOperation {

    private func fetchTeam(for account: ALTAccount, session: ALTAppleAPISession) async throws -> ALTTeam {
        self.verboseLog("[Authentication] fetchTeam: Requesting teams from Apple...")
        let teams = try await AuthManager.shared.fetchTeams(for: account, session: session)
        
        var activeTeamFromDB: Team?
        if let dbContext = self.context.dbBackgroundContext {
            activeTeamFromDB = await dbContext.perform {
                DatabaseManager.shared.activeTeam(in: dbContext)
            }
        }
        
        let selectedTeam: ALTTeam
        if let activeTeam = activeTeamFromDB, let altTeam = teams.first(where: { $0.identifier == activeTeam.identifier }) {
            selectedTeam = altTeam
        } else if teams.count <= 1 {
            if let team = teams.first {
                selectedTeam = team
            } else {
                throw AuthenticationError(.noTeam)
            }
        } else {
            selectedTeam = try await self.context.authenticationHandler.resolveTeam(teams)
        }
        
        self.debugLog("[Authentication] fetchTeam completed successfully ('\(selectedTeam.name)').")
        return selectedTeam
    }

    private func fetchCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let portalCertificates = try await AuthManager.shared.fetchCertificates(for: team, session: session)
        self.context.portalCertificates = portalCertificates
        
        let mainBundleCertSerial = Bundle.main.object(forInfoDictionaryKey: Bundle.Info.certificateID) as? String
        
        if let activeCert = CertificateManager.shared.activeCertificate,
           let certificate = portalCertificates.first(where: { $0.serialNumber == activeCert.serialNumber }) 
        {
            activeCert.certificate.machineIdentifier = certificate.machineIdentifier

            if let mainBundleCertSerial = mainBundleCertSerial, 
                mainBundleCertSerial.lowercased() != activeCert.serialNumber.lowercased() 
            {
                self.debugLog("[Authentication] Active certificate (\(activeCert.serialNumber)) and running bundle certificate (\(mainBundleCertSerial)) mismatch detected. Running Bundle Certificate is still active on the Paid account portal. Using active Keychain certificate.")
            }
            return activeCert.certificate
        }
        
        // TODO: @mahee96: we have moved away from machineID as password for certs, but external/thirdparty like iloader might not have, 
        //                 so we still support the machineId as fallback for now 
        if let mainBundleCertSerial = mainBundleCertSerial,
           let certificate = portalCertificates.first(where: { $0.serialNumber.lowercased() == mainBundleCertSerial.lowercased() }),
           let cert = CertificateManager.shared.getSignableCertificate(for: mainBundleCertSerial, fallbackPassword: certificate.machineIdentifier) 
        {
            cert.machineIdentifier = certificate.machineIdentifier
            self.debugLog("[Authentication] Using running bundle certificate (\(cert.serialNumber)) with valid private key from signable cache.")
            return cert
        }
        
        if portalCertificates.isEmpty {
            // No portalCertificates, so request a new one.
            return try await self.requestCertificate(for: team, session: session)
        } else {
            // We don't have private keys for any of the portalCertificates,
            // so we need to revoke one and create a new one.
            return try await self.replaceCertificate(portalCertificates: portalCertificates, for: team, session: session)
        }
    }

    private func requestCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let deviceName = await UIDevice.current.name
        let machineName: String = "SideStore - \(team.account.firstName)'s \(deviceName)"
        self.verboseLog("[Authentication] Requesting certificate for machineName '\(machineName)'...")

        do {
            let newPortalCertificate = try await AuthManager.shared.addCertificate(machineName: machineName, to: team, session: session)
            self.debugLog("[Authentication] Successfully requested new portal certificate (Serial: \(newPortalCertificate.serialNumber)).")
            
            if self.context.portalCertificates == nil {
                self.context.portalCertificates = []
            }
            self.context.portalCertificates?.append(newPortalCertificate.x509)
            return newPortalCertificate
        } catch {
            self.debugLog("[Authentication] requestCertificate: Failed with error: \(error)")
            let underlying = error as NSError
            if underlying.domain == ALTAppleAPIErrorDomain && 
               underlying.code == ALTAppleAPIError.tooManyCertificates.rawValue 
            {
                let friendlyError: AuthenticationError = (team.type == .free) 
                                        ? AuthenticationError(.certificateLimitReachedFree) 
                                        : AuthenticationError(.certificateLimitReachedPaid)

                let wrappedError = NSError(
                    domain: (friendlyError as NSError).domain,
                    code: (friendlyError as NSError).code,
                    userInfo: [
                        NSLocalizedDescriptionKey: friendlyError.localizedDescription,
                        NSLocalizedFailureReasonErrorKey: friendlyError.failureReason ?? "",
                        NSUnderlyingErrorKey: underlying
                    ]
                )
                throw wrappedError
            } else {
                throw error
            }
        }
    }

    private func replaceCertificate(portalCertificates: [ALTX509Certificate], for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let ourCertificates = portalCertificates.filter { a in
            a.machineName?.starts(with: "SideStore") == true || a.machineName?.starts(with: "AltStore") == true
        }
        self.debugLog("[Authentication] replaceCertificate: Starting. Total certs: \(portalCertificates.count), filtered: \(ourCertificates.count)")
        
        if ourCertificates.isEmpty {
            self.verboseLog("[Authentication] replaceCertificate: None of filtered certificates are of machineName 'SideStore' or 'AltStore'. Requesting new...")
            return try await self.requestCertificate(for: team, session: session)
        }
        
        // We don't have private keys for any of the certificates,
        // so we need to revoke one and create a new one.
        var certsText = ""
        for certificate in ourCertificates {
            if let name = certificate.machineName {
                certsText.append("\(name)\n")
            }
        }
        
        self.debugLog("[Authentication] replaceCertificate: Presenting revoke alert...")
        let action = try await self.context.authenticationHandler.resolveRevocation(certsText: certsText, teamType: team.type)
        self.debugLog("[Authentication] replaceCertificate: User action was \(action)")
        switch action {
            case .keepExisting:
                self.verboseLog("[Authentication] replaceCertificate: Keeping existing, calling requestCertificate...")
                return try await self.requestCertificate(for: team, session: session)
                
            case .revokeAll:
                self.debugLog("[Authentication] replaceCertificate: Revoking all our filtered certificates...")
                var firstError: Error? = nil

                for certificate in ourCertificates {
                    do {
                        self.verboseLog("[Authentication] replaceCertificate: Revoking certificate '\(certificate.machineName ?? "nil")' (Serial: \(certificate.serialNumber))...")
                        try await AuthManager.shared.revokeCertificate(certificate, for: team, session: session)
                        self.verboseLog("[Authentication] replaceCertificate: Revoke succeeded.")
                    } catch {
                        self.debugLog("[Authentication] replaceCertificate: Revoke failed with error: \(error)")
                        if firstError == nil {
                            firstError = error
                        }
                    }
                }

                if let error = firstError {
                    self.debugLog("[Authentication] replaceCertificate: Error occurred during revocation, throwing...")
                    throw error
                } else {
                    self.debugLog("[Authentication] replaceCertificate: All certificates successfully revoked. Requesting new certificate...")
                    return try await self.requestCertificate(for: team, session: session)
                }
        }
    }
    
    @discardableResult
    private func registerCurrentDevice(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTDevice {
        guard let udid = try await fetchUDID() else {
            throw OperationError.unknownUDID
        }
        
        let devices = try await AuthManager.shared.fetchDevices(for: team, types: [.iphone, .ipad], session: session)
        if let device = devices.first(where: { $0.identifier == udid }) {
            return device
        } else {
            return try await AuthManager.shared.registerDevice(name: UIDevice.current.name, identifier: udid, type: .iphone, team: team, session: session)
        }
    }
}
